# Generated by Django 5.0.3 on 2024-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('InicialBid', models.IntegerField()),
                ('Categorie', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=200)),
            ],
        ),
    ]
