# Generated by Django 5.0.3 on 2024-04-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='InicialBid',
            new_name='inicialBid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Name',
        ),
        migrations.AddField(
            model_name='listing',
            name='activeState',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.categories'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
