# Generated by Django 5.0.3 on 2024-04-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='commentText',
        ),
    ]
