# Generated by Django 5.0.3 on 2024-04-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_inicialbid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='inicialBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='auctions.bid'),
        ),
    ]
